import { chromium } from "playwright";
const b = await chromium.launch();
const c = await b.newContext({ viewport:{width:1440,height:900} });
const p = await c.newPage();
const base = process.env.BASE ?? "https://nivora-construcoes.luccaoliveira123.workers.dev";
const tag = process.env.TAG ?? "antes";
await p.goto(base + "/pt/projetos/casa-patio-alto", { waitUntil:"networkidle", timeout:60000 });
await p.evaluate(async()=>{for(let y=0;y<document.body.scrollHeight;y+=500){window.scrollTo(0,y);await new Promise(r=>setTimeout(r,110));}window.scrollTo(0,0);});
await p.waitForTimeout(1200);
const ficha = p.locator("dl").first();
if (await ficha.count()) await ficha.screenshot({ path: `${process.env.OUT}/niv-ficha-${tag}.png` });
await p.goto(base + "/pt", { waitUntil:"networkidle", timeout:60000 });
await p.evaluate(async()=>{window.scrollTo(0,document.body.scrollHeight);await new Promise(r=>setTimeout(r,900));});
await p.waitForTimeout(1000);
await p.locator("footer").first().screenshot({ path: `${process.env.OUT}/niv-rodape-${tag}.png` });
console.log("capturado:", tag);
await b.close();
